name: Dynamic Matrix
# yamllint disable-line rule:truthy
on:
  push:
  workflow_dispatch:
jobs:
  info:  # set $jn to this
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Output
        # https://docs.github.com/en/actions/learn-github-actions/contexts
        # https://docs.github.com/en/actions/learn-github-actions/expressions
        run: echo foo  #"${{ toJSON(github) }}"
        # expression --^^^^^^ ^^^^^^-- context

      - id: set-matrix
        run: |
          #echo "matrix={\"include\": [{\"os\": \"ubuntu-latest\", \"node\": \"20\"}]}" >> "$GITHUB_OUTPUT"
          slack_data_json=$(jq -c -n \
            --arg service_account "${service_account}" \
            --arg project "${project}" \
            --arg rotation_deadline "${rotation_deadline}" \
            --arg created_at "${created_at}" \
            --arg jira_id "${jira_id}" \
            '{
              "include": [
                {
                  "serviceAccount": "sa1",
                  "project": "prj1"
                },
                  "serviceAccount": "sa2",
                  "project": "prj2"
                },
                  "serviceAccount": "sa3",
                  "project": "prj3"
                }
              ]
            }'
          );echo "$slack_data_json"
          echo "matrix=$slack_data_json"

  test:
    needs: info
    strategy:
      matrix: ${{ fromJson(needs.info.outputs.matrix) }}
    runs-on: ubuntu-latest  #${{ matrix.os }}
    steps:
      - run: |
          echo "ONE ${{ matrix.os }} AND ${{ matrix.node }}"
          echo "TWO ${{ matrix.project }} AND ${{ matrix.serviceAccount }}"
